<script lang="ts">
	/*
	 * A question set, asked.
	 *
	 * ONE RENDERER FOR EVERY SET IN Q. Extracted from /questions on 20
	 * September, when block settings were declared as question sets and the
	 * claim "the settings panel is generated by the same renderer that draws
	 * every other question set" would otherwise have been aspirational — a
	 * hand-rolled form beside it would have made it a lie within a week.
	 *
	 * So this draws: Q's own sets, a card's, a place's, a block's settings, and
	 * a federation's plugin — without knowing which is which. A federation
	 * adding a block adds a question set and gets a working form.
	 *
	 * It renders every answer type the schema has. A type it did not handle
	 * would be a question a person cannot answer, silently, so `unsupported`
	 * says so out loud instead.
	 *
	 * Uses (`given`, `shown-to-me`, `pooled`, `modelled`) are shown only when
	 * asked for: a block's settings are not something anybody consents to
	 * sharing, and offering the choice there would be noise that teaches people
	 * to ignore it where it matters.
	 */
	import { asking, USES, type Question, type QuestionSet, type Use } from '@inqbeta/q-core/questions';

	let {
		set,
		values = $bindable({}),
		uses = $bindable({}),
		askUses = false
	}: {
		set: QuestionSet;
		values?: Record<string, unknown>;
		uses?: Record<string, Use[]>;
		askUses?: boolean;
	} = $props();

	const put = (id: string, v: unknown) => (values = { ...values, [id]: v });

	function toggleUse(id: string, use: Use) {
		const had = uses[id] ?? [];
		uses = { ...uses, [id]: had.includes(use) ? had.filter((u) => u !== use) : [...had, use] };
	}

	const handled = (q: Question) =>
		['text', 'did', 'link', 'longtext', 'date', 'number', 'boolean', 'choice', 'questions', 'channels'].includes(q.answer);
</script>

<div class="stack">
	{#each set.questions as q (q.id)}
		<div class="panel stack-tight">
			<label class="block">
				<span class="font-medium">{asking(q)}</span>
				{#if q.optional}<span class="text-xs opacity-60"> — optional</span>{/if}
				{#if q.help?.['en-GB']}<span class="hint block">{q.help['en-GB']}</span>{/if}

				{#if q.answer === 'text' || q.answer === 'did' || q.answer === 'link'}
					<input
						class="input mt-2"
						type={q.answer === 'link' ? 'url' : 'text'}
						inputmode={q.answer === 'link' ? 'url' : undefined}
						value={String(values[q.id] ?? '')}
						oninput={(e) => put(q.id, e.currentTarget.value)}
					/>
				{:else if q.answer === 'longtext'}
					<textarea class="textarea mt-2" rows="3" value={String(values[q.id] ?? '')} oninput={(e) => put(q.id, e.currentTarget.value)}></textarea>
				{:else if q.answer === 'date'}
					<input class="input mt-2" type="date" value={String(values[q.id] ?? '')} oninput={(e) => put(q.id, e.currentTarget.value)} />
				{:else if q.answer === 'number'}
					<input class="input mt-2" type="number" value={String(values[q.id] ?? '')} oninput={(e) => put(q.id, Number(e.currentTarget.value))} />
				{:else if q.answer === 'boolean'}
					<span class="mt-2 flex gap-2">
						<button type="button" class="btn btn-sm {values[q.id] === true ? 'preset-filled-primary-500' : 'preset-outlined-surface-500'}" onclick={() => put(q.id, true)}>Yes</button>
						<button type="button" class="btn btn-sm {values[q.id] === false ? 'preset-filled-primary-500' : 'preset-outlined-surface-500'}" onclick={() => put(q.id, false)}>No</button>
					</span>
				{:else if q.answer === 'choice'}
					<span class="mt-2 flex flex-wrap gap-2">
						{#each q.choices ?? [] as c (c.id)}
							<button type="button" class="btn btn-sm {values[q.id] === c.id ? 'preset-filled-primary-500' : 'preset-outlined-surface-500'}" onclick={() => put(q.id, c.id)}>
								{c.label['en-GB']}
							</button>
						{/each}
					</span>
				{:else if q.answer === 'questions' || q.answer === 'channels'}
					<!-- A list of ids, typed one per line. A picker belongs here and is
					     its own increment; typing works and does not pretend otherwise. -->
					<textarea
						class="textarea mt-2"
						rows="3"
 aria-label="One per line"
						value={(Array.isArray(values[q.id]) ? (values[q.id] as string[]) : []).join('\n')}
						oninput={(e) => put(q.id, e.currentTarget.value.split('\n').map((s) => s.trim()).filter(Boolean))}
					></textarea>
				{/if}
			</label>

			{#if !handled(q)}
				<p class="text-error-600-400 text-sm">
					There is no way to answer this here yet — it asks for “{q.answer}”.
				</p>
			{/if}

			{#if askUses}
				<div class="stack-tight">
					<p class="hint">Answering is <strong>given</strong>, and that is all it is. Anything more is a separate thing to say:</p>
					<div class="flex flex-wrap gap-2">
						{#each USES.filter((u) => u.id !== 'given') as u (u.id)}
							<button
								type="button"
								title={u.says}
								aria-pressed={(uses[q.id] ?? []).includes(u.id)}
								class="btn btn-sm {(uses[q.id] ?? []).includes(u.id) ? 'preset-filled-primary-500' : 'preset-outlined-surface-500'}"
								onclick={() => toggleUse(q.id, u.id)}
							>
								{u.label}
							</button>
						{/each}
					</div>
				</div>
			{/if}
		</div>
	{/each}
</div>
